{% set version = "0.9.21" %}

package:
    name: slacker
    version: {{ version }}

source:
    url: https://github.com/os/slacker/archive/v{{ version }}.tar.gz
    fn: slacker-{{ version }}.tar.gz
    sha256: cc74b71adad43df3e2db027d7d8ea11d2cf669dd178c0b92dfc0cb230040937f

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - setuptools
        - python
    run:
        - python
        - requests

test:
    imports:
        - slacker
about:
    home: https://github.com/os/slacker
    license: Apache 2.0
    summary: Slack API client

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - os
        - tacaswell
