{% set version = "0.9.42" %}
{% set sha = "c344f1487857e68a9104d8e4dea5eb481f5c1daee404c1fc1475fd695360342d" %}

package:
    name: slacker
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/s/slacker/slacker-{{ version }}.tar.gz
    fn: slacker-{{ version }}.tar.gz
    sha256: {{ sha }}

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
    host:
        - setuptools
        - pip
        - python
    run:
        - python
        - requests

test:
    imports:
        - slacker
about:
    home: https://github.com/os/slacker
    license: Apache 2.0
    summary: Slack API client

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - os
        - tacaswell
