{% set name = "slacker" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4c55415096229c1cc616c1504d93672b05521e5499a9be26475e0a9a623c4dc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip 
  run:
    - python
    - requests

test:
  imports:
    - slacker

about:
  home: https://github.com/os/slacker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Slack API client'

extra:
  recipe-maintainers:
   - ericdill
   - licode
   - os
   - tacaswell
   - hadim
