travis:
  secure:
    BINSTAR_TOKEN: Pwpu/4VrzibsZfUfJ3I2YMSc73Jlbg/VyjtuvLxbtsyNv+/8GWodL+ySZxnrvxeXs+jxrFFc1Z0qo8P39nOxe1BNRGukItRX35NrFC2ff9DEte9Anb710lobG7XMT/f+8j1WSK3zuPnN8o8XR996rE6RoLTsXt7eaTvurm55acQFlb2fWC3beHc+f8jStQycy/1S0x7Qd6xT/abEunHGCWFsB4JNb9K5zp8pw6CA367pZNJquK0BOfzIPvAMbGg7Y6BeWvPrwJ1wCC+7rj8HC1CcWNrrV5IEiM/MNAS5fTIX9acFB1lwufCarYYkhTUAQIoz1DtPwIpGZ59O9eWmYdujKjR4fwmuuQHbODeT1CD2CK2vHOXtOvhPRtPwiEKUWiVB1pIyq06rWRKKGFPdRMhb+yiUc9+eTdLCd+yNqibVH2VrwhSMrua5huRXqkPwCZk3fVDR48Ajs1K0HN3a6CYJ/OLTG/utkQ+Vvhar+Yf+wt+BVgAgEXOKvo7PEk1+Nn0mpeoKqohFQAlVTCi213XohOjhZuO76mxQN9VgjDA+RcfqCVtUeVDi1nqTtLm+GQJycmJde7DbmWbD7V19ITKxrny8cE0pA85zD3jpVwzDsj5i5NZoLZynIUm3x3ukazc9YEd4Q35Q36vwSeeSrM/NlzQSz0/ex9xkBq+zYbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
